/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-07-06 17:42:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


String accountHolder = (String) session.getAttribute("accountHolder");
if (accountHolder == null) {
    response.sendRedirect("login.html");
    return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard | ROY BANK</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #ff9a56 0%, #ff6b35 50%, #f7931e 100%);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animated Background */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: \r\n");
      out.write("                radial-gradient(circle at 20% 80%, rgba(255, 154, 86, 0.4) 0%, transparent 50%),\r\n");
      out.write("                radial-gradient(circle at 80% 20%, rgba(255, 107, 53, 0.4) 0%, transparent 50%),\r\n");
      out.write("                radial-gradient(circle at 40% 40%, rgba(247, 147, 30, 0.3) 0%, transparent 50%);\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("            animation: backgroundFloat 20s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes backgroundFloat {\r\n");
      out.write("            0%, 100% { transform: translateY(0px) rotate(0deg); }\r\n");
      out.write("            50% { transform: translateY(-20px) rotate(1deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Sidebar Styles */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border-right: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 2rem 1.5rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("            box-shadow: 8px 0 32px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 107, 53, 0.1), rgba(247, 147, 30, 0.1));\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar h2 {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            padding: 1rem 1.5rem;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05));\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.8rem;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar a::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: left 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar a:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar a:hover {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.15));\r\n");
      out.write("            transform: translateX(5px) scale(1.02);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .sidebar a i {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Content */\r\n");
      out.write("        .main {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 3rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05));\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Welcome Box */\r\n");
      out.write("        .welcome-box {\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            padding: 3rem 2.5rem;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            box-shadow: 0 15px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            animation: welcomeFloat 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes welcomeFloat {\r\n");
      out.write("            0%, 100% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(-10px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-box::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: linear-gradient(45deg, transparent, rgba(255, 255, 255, 0.1), transparent);\r\n");
      out.write("            animation: shimmer 4s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes shimmer {\r\n");
      out.write("            0% { transform: translateX(-100%) translateY(-100%) rotate(45deg); }\r\n");
      out.write("            100% { transform: translateX(100%) translateY(100%) rotate(45deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-box h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome-box p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Quick Stats Cards */\r\n");
      out.write("        .stats-container {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card {\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.15));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card i {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card h3 {\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stat-card p {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            left: 280px;\r\n");
      out.write("            width: calc(100% - 280px);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            body {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("                flex-direction: row;\r\n");
      out.write("                overflow-x: auto;\r\n");
      out.write("                gap: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .sidebar h2 {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .sidebar a {\r\n");
      out.write("                min-width: 120px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding: 0.8rem;\r\n");
      out.write("                font-size: 0.9rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .main {\r\n");
      out.write("                padding: 2rem 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .welcome-box {\r\n");
      out.write("                padding: 2rem 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .welcome-box h1 {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .welcome-box p {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            footer {\r\n");
      out.write("                left: 0;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                position: relative;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Scrollbar Styling */\r\n");
      out.write("        ::-webkit-scrollbar {\r\n");
      out.write("            width: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-track {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ::-webkit-scrollbar-thumb:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h2><i class=\"fas fa-landmark\"></i> ROY BANK</h2>\r\n");
      out.write("        <a href=\"ProfileServlet\"><i class=\"fas fa-user\"></i> View Profile</a>\r\n");
      out.write("        <a href=\"deposit.jsp\"><i class=\"fas fa-piggy-bank\"></i> Deposit</a>\r\n");
      out.write("        <a href=\"withdraw.jsp\"><i class=\"fas fa-money-bill-wave\"></i> Withdraw</a>\r\n");
      out.write("        <a href=\"transfer.jsp\"><i class=\"fas fa-exchange-alt\"></i> Transfer</a>\r\n");
      out.write("        <a href=\"MiniStatementServlet\"><i class=\"fas fa-receipt\"></i> Mini Statement</a>\r\n");
      out.write("        <a href=\"transaction_history.jsp\"><i class=\"fas fa-history\"></i> Transaction History</a>\r\n");
      out.write("        <a href=\"change_pin.jsp\"><i class=\"fas fa-key\"></i> Change PIN</a>\r\n");
      out.write("        <a href=\"update_account.jsp\"><i class=\"fas fa-edit\"></i> Update Info</a>\r\n");
      out.write("        <a href=\"close_account.jsp\"><i class=\"fas fa-user-slash\"></i> Close Account</a>\r\n");
      out.write("        <a href=\"logout.jsp\"><i class=\"fas fa-sign-out-alt\"></i> Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"welcome-box\">\r\n");
      out.write("            <h1>Welcome, ");
      out.print( accountHolder );
      out.write("</h1>\r\n");
      out.write("            <p>Select an action from the left menu to continue banking with us!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"stats-container\">\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <i class=\"fas fa-university\"></i>\r\n");
      out.write("                <h3>Secure Banking</h3>\r\n");
      out.write("                <p>Advanced encryption technology</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <i class=\"fas fa-clock\"></i>\r\n");
      out.write("                <h3>24/7 Service</h3>\r\n");
      out.write("                <p>Round the clock availability</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <i class=\"fas fa-shield-alt\"></i>\r\n");
      out.write("                <h3>Protected</h3>\r\n");
      out.write("                <p>Your money is safe with us</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-card\">\r\n");
      out.write("                <i class=\"fas fa-mobile-alt\"></i>\r\n");
      out.write("                <h3>Mobile Ready</h3>\r\n");
      out.write("                <p>Access anywhere, anytime</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        &copy; 2025 ROY BANK. All rights reserved. | Your Trusted Banking Partner\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
