/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-07-06 16:17:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>ROY BANK | Welcome</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #ff9a56 0%, #ff6b35 25%, #f7931e 50%, #e8751a 75%, #d4641a 100%);\r\n");
      out.write("            background-size: 400% 400%;\r\n");
      out.write("            animation: gradientFlow 15s ease infinite;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("            padding: 2rem 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes gradientFlow {\r\n");
      out.write("            0% { background-position: 0% 50%; }\r\n");
      out.write("            50% { background-position: 100% 50%; }\r\n");
      out.write("            100% { background-position: 0% 50%; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Main Card */\r\n");
      out.write("        .card {\r\n");
      out.write("            background: linear-gradient(145deg, rgba(255, 255, 255, 0.25), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(20px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            box-shadow: 0 15px 50px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            padding: 4rem 3rem;\r\n");
      out.write("            max-width: 850px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            animation: slideUp 1.2s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: linear-gradient(45deg, transparent, rgba(255, 255, 255, 0.1), transparent);\r\n");
      out.write("            animation: shimmer 3s ease-in-out infinite;\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes shimmer {\r\n");
      out.write("            0% { transform: translateX(-100%) translateY(-100%) rotate(45deg); }\r\n");
      out.write("            100% { transform: translateX(100%) translateY(100%) rotate(45deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideUp {\r\n");
      out.write("            from { \r\n");
      out.write("                transform: translateY(50px); \r\n");
      out.write("                opacity: 0; \r\n");
      out.write("            }\r\n");
      out.write("            to { \r\n");
      out.write("                transform: translateY(0); \r\n");
      out.write("                opacity: 1; \r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Header */\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 1rem;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bank-icon {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            animation: pulse 2s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes pulse {\r\n");
      out.write("            0%, 100% { transform: scale(1); }\r\n");
      out.write("            50% { transform: scale(1.1); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Subtitle */\r\n");
      out.write("        p {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            margin-bottom: 3rem;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Button Container */\r\n");
      out.write("        .btn-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Buttons */\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border: 2px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            min-width: 160px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);\r\n");
      out.write("            transition: left 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.primary {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.2));\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.secondary {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.1), rgba(255, 255, 255, 0.05));\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            transform: translateY(-3px) scale(1.05);\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(255, 255, 255, 0.3);\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.2));\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:active {\r\n");
      out.write("            transform: translateY(-1px) scale(1.02);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Features Section */\r\n");
      out.write("        .features {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding-top: 2rem;\r\n");
      out.write("            border-top: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 1.5rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-feature {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.2), rgba(255, 255, 255, 0.1));\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature:hover {\r\n");
      out.write("            transform: translateY(-5px);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-feature:hover {\r\n");
      out.write("            background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.2));\r\n");
      out.write("            transform: translateY(-5px) scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature i {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            animation: glow 2s ease-in-out infinite alternate;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes glow {\r\n");
      out.write("            from { text-shadow: 0 0 10px rgba(255, 255, 255, 0.5); }\r\n");
      out.write("            to { text-shadow: 0 0 20px rgba(255, 255, 255, 0.8), 0 0 30px rgba(255, 255, 255, 0.6); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature h3 {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .feature p {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* About Us Section */\r\n");
      out.write("        .about-section {\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section h2 {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section h2::before {\r\n");
      out.write("            \r\n");
      out.write("            font-family: \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Noto Color Emoji\", sans-serif;\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section p {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            text-align: justify;\r\n");
      out.write("            margin-bottom: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .about-section p:last-child {\r\n");
      out.write("            margin-bottom: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Emoji styling */\r\n");
      out.write("        .emoji {\r\n");
      out.write("            font-style: normal;\r\n");
      out.write("            font-family: \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Noto Color Emoji\", sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Footer */\r\n");
      out.write("        footer {\r\n");
      out.write("            color: rgba(255, 255, 255, 0.8);\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            body {\r\n");
      out.write("                padding: 1rem 0;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .card {\r\n");
      out.write("                padding: 2.5rem 2rem;\r\n");
      out.write("                margin: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            h1 {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("                flex-direction: row;\r\n");
      out.write("                gap: 0.5rem;\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .bank-icon {\r\n");
      out.write("                font-size: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            p {\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("                margin-bottom: 2rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                gap: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .btn {\r\n");
      out.write("                padding: 0.8rem 1.5rem;\r\n");
      out.write("                font-size: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .features {\r\n");
      out.write("                justify-content: center;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .feature {\r\n");
      out.write("                max-width: 100%;\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .about-section {\r\n");
      out.write("                padding: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .about-section h2 {\r\n");
      out.write("                font-size: 1.3rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            body {\r\n");
      out.write("                padding: 0.5rem 0;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .card {\r\n");
      out.write("                padding: 2rem 1.5rem;\r\n");
      out.write("                margin: 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            h1 {\r\n");
      out.write("                font-size: 1.8rem;\r\n");
      out.write("                white-space: normal;\r\n");
      out.write("                line-height: 1.2;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .features {\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("                padding-top: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .about-section {\r\n");
      out.write("                margin-top: 1.5rem;\r\n");
      out.write("                padding: 1rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            Welcome to ROY BANK \r\n");
      out.write("            <i class=\"fas fa-university bank-icon\"></i>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <p>Your trusted partner for secure and smart banking solutions. Experience the future of digital banking with advanced security and seamless transactions.</p>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"btn-container\">\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn primary\">\r\n");
      out.write("                <i class=\"fas fa-sign-in-alt\"></i>\r\n");
      out.write("                Login\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"register.jsp\" class=\"btn secondary\">\r\n");
      out.write("                <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("                Open New Account\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"features\">\r\n");
      out.write("            <div class=\"feature about-feature\">\r\n");
      out.write("                <i class=\"fas fa-crown\"></i>\r\n");
      out.write("                <h3>About ROY BANK</h3>\r\n");
      out.write("                <p>Where Excellence Meets Innovation</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about-section\">\r\n");
      out.write("            <h2>&#127942; Why Choose ROY BANK?</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                <strong>ROY BANK</strong> - Where tradition meets innovation! Founded on the principles of trust, integrity, and customer excellence, we've been transforming lives through smart financial solutions for over two decades. Our state-of-the-art digital banking platform combined with personalized service makes us the preferred choice for modern banking needs.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <span class=\"emoji\">&#128142;</span> <strong>What Makes Us Special:</strong> Advanced AI-powered security systems, 24/7 customer support, lightning-fast transactions, and innovative investment opportunities. Whether you're planning your dream home, starting a business, or securing your family's future, ROY BANK is your trusted financial partner on every step of your journey.\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("                <span class=\"emoji\">&#128640;</span> <strong>Our Vision:</strong> To democratize banking by making premium financial services accessible to everyone, everywhere. Join thousands of satisfied customers who've made ROY BANK their financial home - because your dreams deserve the best banking experience!\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        &copy; 2025 ROY BANK. All rights reserved. | Banking Made Simple\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
