/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-07-06 16:48:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>My Profile | ROY BANK</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #ff9a56 0%, #ffad85 50%, #ffc3a0 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animated background elements */\r\n");
      out.write("        body::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: radial-gradient(circle, rgba(255,255,255,0.1) 1px, transparent 1px);\r\n");
      out.write("            background-size: 50px 50px;\r\n");
      out.write("            animation: float 20s linear infinite;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0% { transform: translateY(0) rotate(0deg); }\r\n");
      out.write("            100% { transform: translateY(-100px) rotate(360deg); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Floating shapes */\r\n");
      out.write("        .floating-shapes {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            pointer-events: none;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .shape {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            animation: floatUp 6s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .shape:nth-child(1) { width: 40px; height: 40px; left: 10%; animation-delay: 0s; }\r\n");
      out.write("        .shape:nth-child(2) { width: 60px; height: 60px; left: 20%; animation-delay: 2s; }\r\n");
      out.write("        .shape:nth-child(3) { width: 80px; height: 80px; left: 80%; animation-delay: 4s; }\r\n");
      out.write("        .shape:nth-child(4) { width: 30px; height: 30px; left: 70%; animation-delay: 1s; }\r\n");
      out.write("        .shape:nth-child(5) { width: 50px; height: 50px; left: 60%; animation-delay: 3s; }\r\n");
      out.write("\r\n");
      out.write("        @keyframes floatUp {\r\n");
      out.write("            0% { transform: translateY(100vh) rotate(0deg); opacity: 0; }\r\n");
      out.write("            10% { opacity: 1; }\r\n");
      out.write("            90% { opacity: 1; }\r\n");
      out.write("            100% { transform: translateY(-100px) rotate(360deg); opacity: 0; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header {\r\n");
      out.write("            background: linear-gradient(135deg, #ff6600, #ff8533, #ffad85);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            box-shadow: 0 4px 20px rgba(255, 102, 0, 0.3);\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: -50%;\r\n");
      out.write("            left: -50%;\r\n");
      out.write("            width: 200%;\r\n");
      out.write("            height: 200%;\r\n");
      out.write("            background: linear-gradient(45deg, transparent, rgba(255,255,255,0.1), transparent);\r\n");
      out.write("            animation: shine 3s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes shine {\r\n");
      out.write("            0% { transform: translateX(-100%) translateY(-100%); }\r\n");
      out.write("            100% { transform: translateX(100%) translateY(100%); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header h1 {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header p {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            z-index: 10;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-card {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border-radius: 24px;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(255, 102, 0, 0.2);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transform: translateY(20px);\r\n");
      out.write("            animation: slideUp 0.8s ease-out forwards;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideUp {\r\n");
      out.write("            to {\r\n");
      out.write("                transform: translateY(0);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-card::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(90deg, #ff6600, #ff8533, #ffad85);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-avatar {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            background: linear-gradient(135deg, #ff6600, #ff8533);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin: 0 auto 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(255, 102, 0, 0.3);\r\n");
      out.write("            animation: pulse 2s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes pulse {\r\n");
      out.write("            0%, 100% { transform: scale(1); }\r\n");
      out.write("            50% { transform: scale(1.05); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-card h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-card .subtitle {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-item {\r\n");
      out.write("            background: rgba(255, 102, 0, 0.05);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            border-left: 4px solid #ff6600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-item::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent);\r\n");
      out.write("            transition: left 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-item:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-item:hover {\r\n");
      out.write("            transform: translateX(5px);\r\n");
      out.write("            box-shadow: 0 5px 20px rgba(255, 102, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-label {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #ff6600;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .info-value {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .balance-highlight {\r\n");
      out.write("            background: linear-gradient(135deg, #ff6600, #ff8533);\r\n");
      out.write("            color: white !important;\r\n");
      out.write("            font-size: 24px !important;\r\n");
      out.write("            font-weight: 700 !important;\r\n");
      out.write("            text-shadow: 1px 1px 2px rgba(0,0,0,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .balance-highlight .info-label {\r\n");
      out.write("            color: rgba(255,255,255,0.9) !important;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background: linear-gradient(135deg, #ff6600, #ff8533);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 16px 32px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(255, 102, 0, 0.3);\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 250px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: -100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(90deg, transparent, rgba(255,255,255,0.3), transparent);\r\n");
      out.write("            transition: left 0.5s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover::before {\r\n");
      out.write("            left: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 12px 35px rgba(255, 102, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn:active {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-gradient {\r\n");
      out.write("            background: linear-gradient(135deg, #ff6600, #ff8533);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            background-clip: text;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive design */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .profile-card {\r\n");
      out.write("                padding: 30px 20px;\r\n");
      out.write("                margin: 20px 15px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            header h1 {\r\n");
      out.write("                font-size: 26px;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .profile-card h2 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"floating-shapes\">\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("        <div class=\"shape\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1>ROY BANK</h1>\r\n");
      out.write("        <p>Your Trusted Financial Partner</p>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"profile-card\">\r\n");
      out.write("            <div class=\"profile-header\">\r\n");
      out.write("                <div class=\"profile-avatar\">\r\n");
      out.write("                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name.charAt(0)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Account Profile</h2>\r\n");
      out.write("                <p class=\"subtitle\">Welcome back to your personal banking dashboard</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"info-grid\">\r\n");
      out.write("                <div class=\"info-item\">\r\n");
      out.write("                    <div class=\"info-label\">Account Number</div>\r\n");
      out.write("                    <div class=\"info-value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accNum}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"info-item\">\r\n");
      out.write("                    <div class=\"info-label\">Full Name</div>\r\n");
      out.write("                    <div class=\"info-value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"info-item\">\r\n");
      out.write("                    <div class=\"info-label\">Contact Information</div>\r\n");
      out.write("                    <div class=\"info-value\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contact}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"info-item balance-highlight\">\r\n");
      out.write("                    <div class=\"info-label\">Current Balance</div>\r\n");
      out.write("                    <div class=\"info-value\">₹");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${balance}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"dashboard.jsp\" class=\"btn\">\r\n");
      out.write("                🏠 Go to Dashboard\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>&copy; 2025 <span class=\"footer-gradient\">ROY BANK</span>. All rights reserved.</p>\r\n");
      out.write("        <p>Secure • Reliable • Trusted</p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
